### ISSUE TITLE
write 'updateObject' function for new GenomicInteractions class definition

### ISSUE THREAD

**Issue by liz-is** [ComputationalRegulatoryGenomicsICL/GenomicInteractions-old#25]
after switchover to iset backend

see: http://svitsrv25.epfl.ch/R-doc/library/Biobase/html/updateObject.html

**Comment by liz-is** [comment]
Done in https://github.com/ComputationalRegulatoryGenomicsICL/GenomicInteractions/commit/4d4d794cb4e55d9f7fe93583db7a483bddd14ee9 - @mgperry does the conversion look okay?

To do: convert and resave data objects.

**Comment by mgperry** [comment]
Looks good, I will test this with any data I have lying around.
