### ISSUE TITLE
How to intersect of two GenomicInteraction Objects? 

### ISSUE THREAD

**Issue by Zefeng-Wu** [ComputationalRegulatoryGenomicsICL/GenomicInteractions-old#32]
Hi, How to intersect of two GenomicInteraction Objects?  For example how to inspect whether a pair of genes have interaction by reads number supports ?

**Comment by liz-is** [comment]
Hi, 

Please see the InteractionSet [vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/InteractionSet/inst/doc/interactions.html) for overlap methods. You can overlap two GenomicInteractions objects using: `findOverlaps(gi1, gi2)`. Or check whether interactions link any pairs of genes using: `linkOverlaps(gi, my_genes)` where my_genes is a GRanges containing locations of your genes of interest.

Hope that helps, and sorry for the delayed response. If you have future questions, you can post them on the[ Bioconductor support site](https://support.bioconductor.org/) where they will be visible to more people who might be able to answer them!

**Comment by Zefeng-Wu** [comment]
Thanks for your reply, it really can solve my question.
