### ISSUE TITLE
Highlight specific interaction 

### ISSUE THREAD

**Issue by tiagochst** [ComputationalRegulatoryGenomicsICL/GenomicInteractions-old#33]
Please, is it possible to give a different color to an specify interaction?

**Comment by mgperry** [comment]
Hi Tiago, I don't think this is currently possible using GenomicInteractions, and would be tricky to implement. For now it's probably easiest to save your image as a PDF, then edit it in Illustrator or inkscape to change the colour/thickness of that particular interaction.

Hope that helps!

Malcolm
