### ISSUE TITLE
update plotting code to work with gviz

### ISSUE THREAD

**Issue by iwanttobeabadger** [ComputationalRegulatoryGenomicsICL/GenomicInteractions-old#7]

**Comment by liz-is** [comment]
It'd be nice if the viewpoints plotting code was also Gviz-integrated. As a barplot or line plot perhaps?

**Comment by mgperry** [comment]
I'm intending to go over the viewpoints code at some point. It would be good if we used the same Gviz wrapper for both, @iwanttobeabadger can you make sure that's reuseable?
